---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# regexcite

<!-- badges: start -->
<!-- badges: end -->

This is a toy package I made just for practice.

## Installation

You can install the development version of regexcite from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("przybylee/regexcite")
```

## Usage

Often, we want to split a single string into a vector of strings.  In `base::strsplit()` this looks like
```{r example}
x <- "what,would,you,do,if,I,sang,outa,tune"
strsplit(x,split = ",")
```

Using `stringr::str_split()`, we get
```{r}
stringr::str_split(x, pattern = ",")
```

If we prefer the value be an unlisted character vector, we can use `regexcite::str_split_one()`.

```{r}
library(regexcite)

str_split_one(x, pattern = ",")
```

